
title: Simulaties natuurkunde
author: Henk Tober
logo: logo.png

execute:
  execute_notebooks: force
  raise_on_error: true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"
  thebe: true

repository:
  url: https://github.com/HenkTober/Simulaties
  path_to_book: .
  branch: main

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
      - https://unpkg.com/thebe@latest/lib/index.js
      - https://unpkg.com/@jupyter-widgets/html-manager@latest/dist/embed-amd.js

    html_css_files:
      - https://cdnjs.cloudflare.com/ajax/libs/jupyter-widgets/7.6.5/widgets.min.css

    thebe_config:
      use_thebe_lite: false
      binderhub_url: "https://mybinder.org"
      repository_url: "https://github.com/HenkTober/Simulaties"
      ref: "main"
      selector: ".thebe-cell"
      codemirror_theme: "abcdef"
