
title: Simulaties natuurkunde
author: Henk Tober
logo: logo.png
copyright: ""

build:
  requirements: requirements.txt

execute:
  execute_notebooks: force
  raise_on_error: true


repository:
  url: https://github.com/HenkTober/Simulaties
  path_to_book: .
  branch: main

launch_buttons:
  thebe: true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]


thebe_config:
      use_thebe_lite: false
      binderhub_url: "https://mybinder.org"
      repository_url: "https://github.com/HenkTober/Simulaties"
      ref: "main"
      selector: ".thebe-cell"
      codemirror_theme: "abcdef"


